name: Github CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-runner:
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build And Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: runner
          tags: ghcr.io/isKONSTANTIN/telegram-gpt-runner:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}

  build-and-push-migrator:
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build And Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: migrator
          tags: ghcr.io/isKONSTANTIN/telegram-gpt-migrator:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}